package com.shihuc.up.nav.path.dao;

import com.shihuc.up.nav.path.model.DijPoint;

import java.util.List;

public interface DijPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dij_point
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dij_point
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    int insert(DijPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dij_point
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    DijPoint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dij_point
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    List<DijPoint> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dij_point
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    int updateByPrimaryKey(DijPoint record);
}