package com.shihuc.up.nav.path.model;

public class DijEdge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dij_edge.id
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dij_edge.point
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    private Integer point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dij_edge.neighbor
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    private Integer neighbor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dij_edge.weight
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    private Integer weight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dij_edge.id
     *
     * @return the value of dij_edge.id
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dij_edge.id
     *
     * @param id the value for dij_edge.id
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dij_edge.point
     *
     * @return the value of dij_edge.point
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dij_edge.point
     *
     * @param point the value for dij_edge.point
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dij_edge.neighbor
     *
     * @return the value of dij_edge.neighbor
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    public Integer getNeighbor() {
        return neighbor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dij_edge.neighbor
     *
     * @param neighbor the value for dij_edge.neighbor
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    public void setNeighbor(Integer neighbor) {
        this.neighbor = neighbor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dij_edge.weight
     *
     * @return the value of dij_edge.weight
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dij_edge.weight
     *
     * @param weight the value for dij_edge.weight
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
}