package com.shihuc.up.nav.path.model;

public class DijPoint {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dij_point.id
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dij_point.pointx
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    private Integer pointx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dij_point.pointy
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    private Integer pointy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dij_point.id
     *
     * @return the value of dij_point.id
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dij_point.id
     *
     * @param id the value for dij_point.id
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dij_point.pointx
     *
     * @return the value of dij_point.pointx
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    public Integer getPointx() {
        return pointx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dij_point.pointx
     *
     * @param pointx the value for dij_point.pointx
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    public void setPointx(Integer pointx) {
        this.pointx = pointx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dij_point.pointy
     *
     * @return the value of dij_point.pointy
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    public Integer getPointy() {
        return pointy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dij_point.pointy
     *
     * @param pointy the value for dij_point.pointy
     *
     * @mbg.generated Wed Dec 11 09:18:09 CST 2019
     */
    public void setPointy(Integer pointy) {
        this.pointy = pointy;
    }
}